baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Food'
pageRef = '/drinks'
weight = 20

[[menus.main]]
name = 'Drinks'
pageRef = '/drinks'
weight = 20

[[menus.main]]
name = 'Catering'
pageRef = '/drinks'
weight = 20

[[menus.main]]
name = 'Reservations'
pageRef = '/drinks'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/posts'
weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
