baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Menu'
pageRef = '/menu'
weight = 10

[[menus.main]]
name = 'Drinks'
pageRef = '/drinks'
weight = 20

[[menus.main]]
name = 'Catering'
pageRef = '/catering'
weight = 30

[[menus.main]]
name = 'Parties'
pageRef = '/parties'
weight = 40

[[menus.main]]
name = 'Order'
pageRef = '/order'
weight = 50

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 60

[[menus.main]]
name = 'Blog'
pageRef = '/posts'
weight = 70

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
