backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/img
public_folder: /img
collections:
  - name: "landingPages"
    label: "Landing Pages"
    widget: list
    files:
      - label: "Home"
        name: "home"
        file: "data/homepage.yml"
        editor:
          preview: false
        fields:
          - label: "Hero"
            name: "hero"
            widget: object
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - { label: "Lede", name: 'lede', widget: 'string' }
          - label: "Happy Hour"
            name: "happyHour"
            widget: object
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - label: "Hours"
                name: "hours"
                widget: list
                fields:
                  - { label: "Days", name: "days", widget: "string" }
                  - { label: "Hours", name: "hours", widget: "string" }
          - label: "Brunch"
            name: "brunch"
            widget: object
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - label: "Hours"
                name: "hours"
                widget: list
                fields:
                  - { label: "Days", name: "days", widget: "string" }
                  - { label: "Hours", name: "hours", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - label: "Call to Action"
                name: "cta"
                widget: object
                fields:
                  - { label: "Button Text", name: "buttonText", widget: "string" }
                  - label: "Link"
                    name: "link"
                    widget: "relation"
                    collection: "landingPages"
                    file: "homepage"
                    value_field: "name"
                    search_fields: ["label"]
  - name: "productDescriptions"
    label: "Product Descriptions"
    folder: "content/products"
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Photo"
        name: "photo"
        widget: "image"
      - label: "Icon"
        name: "icon"
        widget: "string"
  - name: "drinks"
    label: "Drink Menu"
    folder: "content/drinks"
    create: true
    editor:
      preview: false
    fields:
      - label: "Drinks"
        name: "drinks"
        widget: list
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Options"
            name: "options"
            widget: "select"
            options: ["Hot", "Cold", "Sparkling", "Rosé", "White", "Red"]
            default: "Hot"
          - label: Size and Price
            name: sizeAndPrice
            widget: list
            fields:
              - { label: Price, name: price, widget: string }
              - { label: Size, name: size, widget: select, options: ["8oz.", "16oz.", "20oz.", "24oz.", "By Glass"] }
  - name: 'blog'
    label: 'Blog'
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }