backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/img
public_folder: /img
collections:
  - label: "Landing Pages"
    name: "sitePages"
    create: true
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "data/homepage.yml"
        editor:
          preview: false
        fields:
          - label: "Hero"
            name: "hero"
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - { label: "Lede", name: 'lede', widget: 'string' }
          - label: "Happy Hour Feature"
            name: "happyHour"
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - label: "Hours"
                name: "hours"
                widget: list
                fields:
                  - { label: "Days", name: "days", widget: "string" }
                  - { label: "Hours", name: "hours", widget: "string" }
                required: false
          - label: "Brunch Feature"
            name: "brunch"
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - label: "Hours"
                name: "hours"
                widget: list
                fields:
                  - { label: "Days", name: "days", widget: "string" }
                  - { label: "Hours", name: "hours", widget: "string" }
                required: false
              - { label: "Description", name: "description", widget: "string", required: false }
              - label: "Call to Action"
                name: "cta"
                widget: object
                fields:
                  - { label: "Button Text", name: "buttonText", widget: "string", required: false }
                  - label: "Link"
                    name: "link"
                    widget: "relation"
                    collection: "sitePages"
                    value_field: "name"
                    search_fields: ["label"]
                    required: false
                required: false
          - label: "Specials"
            name: "specials"
            widget: "object"
            collapsed: true
            fields:
              - label: "Heading"
                name: "heading"
                widget: "string"
              - label: "Details"
                name: "details"
                widget: "list"
                fields:
                  - { label: "Line", name: "line", widget: "string" }
              - label: "Photo"
                name: "photo"
                widget: image
          - label: "Products"
            name: "products"
            widget: object
            collapsed: true
            fields:
              - label: "Title"
                name: "title"
              - label: "Description"
                name: "description"
              - label: "Products"
                name: "products"
                widget: list
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "text"
                  - label: "Photo"
                    name: "photo"
                    widget: "image"
                  - label: "Photo Alt Text"
                    name: "photoAltText"
                    widget: "string"
                    required: false
      - label: "Drinks"
        name: "drinks"
        file: "data/drinks.yml"
        editor:
          preview: false
        fields:
          - label: "Drinks Description"
            name: "drinksDescription"
            widget: "string"
          - label: "Hot Drinks"
            name: "hotDrinks"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Size and Price
                name: sizeAndPrice
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
                  - { label: Size, name: size, widget: select, options: ["8oz.", "16oz.", "20oz.", "24oz."] }
          - label: "Cold Drinks"
            name: "coldDrinks"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Size and Price
                name: sizeAndPrice
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
                  - { label: Size, name: size, widget: select, options: ["8oz.", "16oz.", "20oz.", "24oz."] }
          - label: "Wines by the Glass Description"
            name: "winesByTheGlassDescription"
            widget: "string"
          - label: "Sparkling"
            name: "sparkling"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Price
                name: price
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
          - label: "Rosé"
            name: "rose"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Price
                name: price
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
          - label: "White"
            name: "white"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                fields:
                  - label: Price
                    name: price
                    widget: list
                    fields:
                      - { label: Price, name: price, widget: string }
          - label: "Red"
            name: "red"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Price
                name: price
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
      - label: "Food"
        name: "Food"
        file: "data/food.yml"
        editor:
          preview: false
        fields:
          - label: "Menus"
            name: "menus"
            widget: "list"
            fields:
              - label: "Menu Name"
                name: "menu_name"
                widget: "string"
              - label: "Menu Description"
                name: "menu_description"
                widget: "text"
                required: false
              - label: "Menu Sections"
                name: "menu"
                widget: "list"
                fields:
                  - label: "Section Title"
                    name: "menu_section"
                    widget: "string"
                  - label: "Section Description"
                    name: "menu_section_description"
                    widget: "text"
                    required: false
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    collapsed: true
                    fields:
                      - label: "Title"
                        name: "title"
                        widget: "string"
                      - label: "Description"
                        name: "description"
                        widget: "text"
                        required: false
                      - label: "Designation"
                        name: "designation"
                        widget: "select"
                        multiple: true
                        required: false
                        options:
                          - { label: "Gluten Free", value: "GF" }
                          - { label: "Vegetarian", value: "V" }
                          - { label: "Vegan", value: "VE" }
                      - label: "Options"
                        name: "options"
                        widget: "list"
                        fields:
                          - { label: Size, name: size, widget: select, options: ["8oz.", "16oz.", "20oz.", "24oz."], required: false }
                          - { label: Price, name: price, widget: string }
                      - label: Photo
                        name: photo
                        widget: image
                        required: false
        # fields:
        #   - label: "Breakfast Sandwiches"
        #     name: "breakfastSandwiches"
        #     widget: "object"
        #     collapsed: true
        #     fields:
        #       - label: "Title"
        #         name: "title"
        #         widget: "string"
        #       - label: "Description"
        #         name: "description"
        #         widget: "text"
        #         required: false
        #       - label: Breakfast Sandwiches
        #         name: breakfastSandwiches
        #         widget: list
        #         fields:
        #           - { label: Title, name: title, widget: string }
        #           - label: Designation
        #             name: designation
        #             widget: select
        #             multiple: true
        #             options:
        #               - { label: "Gluten Free", value: "GF" }
        #               - { label: "Vegetarian", value: "V" }
        #               - { label: "Vegan", value: "VE" } 
        #             required: false
        #           - { label: Description, name: description, widget: text }
        #           - { label: Price, name: price, widget: string }
        #           - { label: Photo, name: photo, widget: image, required: false }
  - name: 'blog'
    label: 'Blog'
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # - label: "Components"
  #   name: "components"
  #   fields:
  #     - label: "Featured Products"
  #       name: "featured_products"
  #       fields:
  #         - label: "Heading"
  #           name: "heading"
  #           widget: "string"
  #         - label: "Body"
  #           name: "body"
  #           widget: "markdown"
  #     - label: "Featured Dishes"
  #       name: "featured_dishes"
