backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/img
public_folder: /img
collections:
  - label: "Landing Pages"
    name: "sitePages"
    create: true
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "data/homepage.yml"
        editor:
          preview: false
        fields:
          - label: "Hero"
            name: "hero"
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - { label: "Lede", name: 'lede', widget: 'string' }
          - label: "Happy Hour Feature"
            name: "happyHour"
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - label: "Hours"
                name: "hours"
                widget: list
                fields:
                  - { label: "Days", name: "days", widget: "string" }
                  - { label: "Hours", name: "hours", widget: "string" }
                required: false
          - label: "Brunch Feature"
            name: "brunch"
            widget: object
            collapsed: true
            fields:
              - { label: "Heading", name: 'heading', widget: 'string' }
              - label: "Hours"
                name: "hours"
                widget: list
                fields:
                  - { label: "Days", name: "days", widget: "string" }
                  - { label: "Hours", name: "hours", widget: "string" }
                required: false
              - { label: "Description", name: "description", widget: "string", required: false }
              - label: "Call to Action"
                name: "cta"
                widget: object
                fields:
                  - { label: "Button Text", name: "buttonText", widget: "string", required: false }
                  - label: "Link"
                    name: "link"
                    widget: "relation"
                    collection: "sitePages"
                    value_field: "name"
                    search_fields: ["label"]
                    required: false
                required: false
          - label: "Products"
            name: "products"
            widget: object
            collapsed: true
            fields:
              - label: "Title"
                name: "title"
              - label: "Description"
                name: "description"
              - label: "Products"
                name: "products"
                widget: list
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "text"
                  - label: "Photo"
                    name: "photo"
                    widget: "image"
                  - label: "Photo Alt Text"
                    name: "photoAltText"
                    widget: "string"
                    required: false
      - label: "Drinks"
        name: "drinks"
        file: "data/drinks.yml"
        editor:
          preview: false
        fields:
          - label: "Drinks Description"
            name: "drinksDescription"
            widget: "string"
          - label: "Hot Drinks"
            name: "hotDrinks"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Size and Price
                name: sizeAndPrice
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
                  - { label: Size, name: size, widget: select, options: ["8oz.", "16oz.", "20oz.", "24oz."] }
          - label: "Cold Drinks"
            name: "coldDrinks"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Size and Price
                name: sizeAndPrice
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
                  - { label: Size, name: size, widget: select, options: ["8oz.", "16oz.", "20oz.", "24oz."] }
          - label: "Wines by the Glass Description"
            name: "winesByTheGlassDescription"
            widget: "string"
          - label: "Sparkling"
            name: "sparkling"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Price
                name: price
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
          - label: "Rosé"
            name: "rose"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Price
                name: price
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
          - label: "White"
            name: "white"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                fields:
                  - label: Price
                    name: price
                    widget: list
                    fields:
                      - { label: Price, name: price, widget: string }
          - label: "Red"
            name: "red"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: Price
                name: price
                widget: list
                fields:
                  - { label: Price, name: price, widget: string }
  - name: 'blog'
    label: 'Blog'
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }